- name: Lab Challenge
  hosts: all
  become: true

  tasks:
    - name: install several packages
      apt:
        name:
          - npm
          - nodejs
          - git
          - pwgen
          - unzip
          - python3-virtualenv
          - python3-pip
        state: present

    - name: add docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository: repo="deb https://download.docker.com/linux/ubuntu jammy stable" state=present

    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        state: latest

    - name: start docker
      service:
        name: docker
        state: started

    - name: add student to docker group
      user:
        name: student
        groups: docker
        append: yes

    - name: pip module to install docker-compose
      pip:
        name: docker-compose
        executable: pip3
